Repository tusharojha/web_scraper, pull requests merged in 2020-11, with the labels that each got.

#9 Added URL Validation
  example/android/app/build.gradle
  example/lib/main.dart
  example/pubspec.lock
  example/pubspec.yaml
  lib/validation.dart
  lib/web_scraper.dart
  pubspec.lock
  pubspec.yaml
  test/validation_test.dart
Labels: enhancement, hacktoberfest-accepted

#11 Update README.md
  README.md
Labels: hacktoberfest-accepted

#16 Version Launch 0.0.7
  CHANGELOG.md
  README.md
  example/pubspec.lock
  lib/validation.dart
  lib/web_scraper.dart
  pubspec.yaml
Labels: enhancement
